model:
  target: models.autoencoders.autoencoder.AutoencoderKL
  params:
    learning_rate: 4.5e-6
    embed_dim: 8
    loss:
      target: models.autoencoders.losses.disc_loss.VQLPIPSWithDiscriminator
      params:
        codebook_term: False
        disc_conditional: False
        disc_in_channels: 3 # The number of input channels to the discriminator (3 for RGB)
        disc_start_iter: 1000 # The number of **iterations** after which the discriminator kicks in # TODO: less than 5000 but higher than 1000 (for two gpus)
        disc_weight: 0.5 #  The weight of the discriminator loss in the overall loss function.
        kll_weight: 0.000001 # The weight of the codebook loss in the overall loss function.
        percept_loss:
          target: models.autoencoders.losses.lpips.LPIPS
          params:
            eval_mode: True
            perceptual_weight: 0.5
            perceptual_start_iter: 1
    ddconfig:
      double_z: True
      z_channels: 8 
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 64
      ch_mult: [ 1,2,2,4] 
      num_res_blocks: 1 
      attn_resolutions: [ ]
      dropout: 0.0